10 REM SIMPLE CALCULATOR
20 PRINT "SIMPLE CALCULATOR"
30 PRINT "ENTER FIRST NUMBER:"
40 INPUT A
50 PRINT "ENTER SECOND NUMBER:"
60 INPUT B
70 PRINT "A + B ="; A+B
80 PRINT "A - B ="; A-B
90 PRINT "A * B ="; A*B
100 PRINT "A / B ="; A/B
110 END
